//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.RHS.EnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class latest_scores
    {
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public System.DateTime ins_date { get; set; }
        public string ins_score { get; set; }
        public string ins_grade { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> zip { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lng { get; set; }
    }
}
